<?php

namespace DHIS\Bundle\CommonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends EntityRepository
{
    /**
     * Check whether group already exist or not.
     * 
     * @param Group $group
     * @return boolean
     */
    public function isExist(Group $group)
    {
        $other = $this->findOneBy(array(
            'name' => $group->getName()
        ));
        
        if ($other) {
            if ($other->getId() === $group->getId())
                return false;
            else
                return true;
        }
        
        return false;
    }
    
    /**
     * Save.
     * 
     * @param Group $group
     * @throws \InvalidArgumentException 
     */
    public function saveGroup(Group $group)
    {
        $manager = $this->getEntityManager('common');
        
        if ($this->isExist($group)) {
            throw new \InvalidArgumentException('Error: Duplicated group.');
        }
        
        $manager->persist($group);
        $manager->flush();
    }
}