imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

parameters:
    knp_paginator.template.pagination: DHISCommonBundle::pagination.html.twig

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resource:
            - "DHISCommonBundle::form.html.twig"

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: common
        connections:
            common:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name_common%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
            scomdis:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name_scomdis%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
            pm1:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name_pm1%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
            eyebase:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name_eyebase%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
#            auth:
#                driver:   %auth_database_driver_auth%
#                host:     %auth_database_host%
#                port:     %auth_database_port%
#                dbname:   %auth_database_name%
#                user:     %auth_database_user%
#                password: %auth_database_password%
#                charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
#        auto_mapping: true
        default_entity_manager:   common
        entity_managers:
            common:
                connection:   common
                mappings:
                    DHISCommonBundle:   ~
            scomdis:
                connection:   scomdis
                mappings:
                    DHISSComDisBundle:  ~
            pm1:
                connection:   pm1
                mappings:
                    DHISPM1Bundle:      ~
            eyebase:
                connection:   eyebase
                mappings:
                    DHISEyeBaseBundle:  ~
 #           auth:
 #               connection:   auth
 #               mappings:
 #                   DHISCommonBundle:   ~

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

stof_doctrine_extensions:
  orm:
      common:
          timestampable: true
      scomdis:
          timestampable: true
      pm1:
          timestampable: true
      eyebase:
          timestampable: true
