DHISAdminBundle:
    resource: "@DHISAdminBundle/Controller/"
    type:     annotation
    prefix:   /

homepage:
    pattern: /
    defaults: { _controller: DHISCommonBundle:Default:index }

auth:
    resource: "@DHISCommonBundle/Controller/SecurityController.php"
    type:     annotation

DHISCommonBundle:
    resource: "@DHISCommonBundle/Controller/"
    type:     annotation
    prefix:   /

DHISComDisBundle:
    resource: "@DHISSComDisBundle/Controller/"
    type:     annotation

DHISEyeBaseBundle:
    resource: "@DHISEyeBaseBundle/Controller/"
    type:     annotation

DHISPM1Bundle:
    resource: "@DHISPM1Bundle/Controller/"
    type:     annotation

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
