services:
  surveillance.carec_report_service:
    class: DHIS\Bundle\SComDisBundle\Service\CARECReportService
    arguments:
      - @doctrine
  surveillance.dailly_tally_report_service:
    class: DHIS\Bundle\SComDisBundle\Service\DailyTallyReportService
    arguments:
      - @doctrine
  surveillance.chart_service:
    class: DHIS\Bundle\SComDisBundle\Service\ChartService
    arguments:
      - @doctrine
  surveillance.dailly_tally_import_service:
    class: DHIS\Bundle\SComDisBundle\Service\DailyTallyImportService
    arguments:
      - @doctrine
