<?php

namespace DHIS\Bundle\SComDisBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BBSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BBSRepository extends EntityRepository
{
    public function postMessage(BBS $bbs)
    {
        $manager = $this->getEntityManager();
        $manager->persist($bbs);        
        $manager->flush();
    }
}