<?php

namespace DHIS\Bundle\SComDisBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DistrictRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistrictRepository extends EntityRepository
{
    /**
     * Find All District.
     * 
     * @return array $districts
     */
    public function findAll()
    {
        $districts = parent::findAll();
        $this->updatePopulationRatio($districts, $this->getTotalPopulation($districts));
        return $districts;
        
    }
    
    protected function getTotalPopulation($districts)
    {
        $total = 0;
        foreach ($districts as $district) {
            $total += $district->getPopulation();
        }
        return $total;
    }
    
    protected function updatePopulationRatio(&$districts, $totalPopulation)
    {
        foreach ($districts as $district) {
            $district->updateRatio($totalPopulation);
        }
    }
}