<?php

namespace DHIS\Bundle\SComDisBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogRepository extends EntityRepository
{
    /**
     * Save.
     * 
     * @param Log $log
     */
    public function saveMessage(Log $log)
    {           
        $manager = $this->getEntityManager();
        $manager->persist($log);
        $manager->flush();
    }
}